
const List<String> shieldList = [
  'assets/shields/Alianza-Petrolera.png',
  'assets/shields/America-de-Cali.png',
  'assets/shields/Atletico-Nacional.png',
  'assets/shields/Boyaca-Chico.png',
  'assets/shields/Bucaramanga.png',
  'assets/shields/Deportivo-Cali.png',
  'assets/shields/Envigado.png',
  'assets/shields/Huila.png',
  'assets/shields/Junior.png',
  'assets/shields/Medellin.png',
  'assets/shields/Millonarios.png',
  'assets/shields/Once-Caldas.png',
  'assets/shields/Pasto.png',
  'assets/shields/Pereira.png',
  'assets/shields/Quindio.png',
  'assets/shields/Rionegro-Aguilas.png',
  'assets/shields/Santa-Fe.png',
  'assets/shields/Tolima.png',
  'assets/shields/Union-Magdalena.png',
];
const Map<String, String> shieldFormMap = {
  'assets/shields/Alianza-Petrolera.png': 'Alianza-Petrolera.png',
  'assets/shields/America-de-Cali.png': 'America-de-Cali.png',
  'assets/shields/Atletico-Nacional.png': 'Atletico-Nacional.png',
  'assets/shields/Boyaca-Chico.png': 'Boyaca-Chico.png',
  'assets/shields/Bucaramanga.png': 'Bucaramanga.png',
  'assets/shields/Deportivo-Cali.png': 'Deportivo-Cali.png',
  'assets/shields/Envigado.png': 'Envigado.png',
  'assets/shields/Huila.png': 'Huila.png',
  'assets/shields/Junior.png': 'Junior.png',
  'assets/shields/Medellin.png': 'Medellin.png',
  'assets/shields/Millonarios.png': 'Millonarios.png',
  'assets/shields/Once-Caldas.png': 'Once-Caldas.png',
  'assets/shields/Pasto.png': 'Pasto.png',
  'assets/shields/Pereira.png': 'Pereira.png',
  'assets/shields/Quindio.png': 'Quindío.png',
  'assets/shields/Rionegro-Aguilas.png': 'Rionegro-Aguilas.png',
  'assets/shields/Santa-Fe.png': 'Santa-Fe.png',
  'assets/shields/Tolima.png': 'Tolima.png',
  'assets/shields/Union-Magdalena.png': 'Union-Magdalena.png',
};
